services:
  - type: web
    name: gd-lite-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "6080"
      - key: KVM
        value: "false"
      - key: DEVICE
        value: "Samsung Galaxy S6"
